### ISSUE TITLE
Unnecessary lock? and other changes in forks

### ISSUE THREAD

**Issue by 0joshuaolson1** [sean-public/fast-skiplist#5]
Hi, I see a couple possible enhancements in forks with un-PR'd commits:

- (see "remove locking") https://github.com/sean-public/fast-skiplist/compare/master...pilosa:master
- (`Back()`) https://github.com/sean-public/fast-skiplist/compare/master...JakeCooper:master

**Comment by sean-public** [comment]
Hi, I know about those; some people wanted a lock-free version so they've removed the locks. I think there is no action for this issue so I am closing it.
