### ISSUE TITLE
SetMaxLevel can alter existing data?

### ISSUE THREAD

**Issue by 0joshuaolson1** [sean-public/fast-skiplist#7]
The [docs](https://github.com/sean-public/fast-skiplist/blob/f96cf8382b81b4bd5eb0afa2f876a7b4074e2111/skiplist.go#L129) [claim](https://godoc.org/github.com/sean-public/fast-skiplist#SkipList.SetMaxLevel) that it doesn't.

In [the function's code](https://github.com/sean-public/fast-skiplist/blob/master/skiplist.go#L132), downsizing "truncates" (eventually GC'd/overwritten?) and upsizing moves/copies, invalidating pointers when [iterating over elements](https://github.com/sean-public/fast-skiplist/issues/6)?

**Comment by sean-public** [comment]
The values remain the same; the links between the nodes can be altered. I doubt there will be many use cases for changing the `MaxLevel` once a list is created, so I will remove that feature.
